import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Footer from '@/app/(landing)/_components/Footer';
import Header from '@/app/(landing)/_components/Header';
import Providers from '@/app/providers';
import SelectTour from './(landing)/_components/SelectTour';
import ChooseTours from './(landing)/_components/ChooseTours';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Providers>
          <Header />
          <SelectTour />
          <ChooseTours />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
